In [4]:
#Regression model from stratch and builtin
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)
np.random.seed(42)

# 100 samples with 1 feature
X = 2 * np.random.rand(100, 1)

# linear equation with noise
y = 4 + 3 * X.flatten() + np.random.randn(100)

print("FIRST 10 FEATURE VALUES (X)")
print(X[:10])

print("\nFIRST 10 TARGET VALUES (y)")
print(y[:10])

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("\nTRAINING DATA SIZE")
print(X_train.shape)
print("\nTESTING DATA SIZE")
print(X_test.shape)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("\nFIRST 10 PREDICTIONS")
print(y_pred[:10])

def mae(actual, predicted):
    return np.mean(np.abs(actual - predicted))

def mse(actual, predicted):
    return np.mean((actual - predicted) ** 2)

def rmse(actual, predicted):
    mse = np.mean((actual - predicted) ** 2)
    return np.sqrt(mse)
    
def r2(actual, predicted):
    ss_total = np.sum((actual - np.mean(actual)) ** 2)
    ss_residual = np.sum((actual - predicted) ** 2)
    return 1 - (ss_residual / ss_total)

mae_manual = mae(y_test, y_pred)
mse_manual = mse(y_test, y_pred)
rmse_manual = rmse(y_test, y_pred)
r2_manual = r2(y_test, y_pred)

print("\nMANUAL METRICS")
print("MAE  =", mae_manual)
print("MSE  =", mse_manual)
print("RMSE =", rmse_manual)
print("R2   =", r2_manual)

mae_builtin = mean_absolute_error(y_test, y_pred)
mse_builtin = mean_squared_error(y_test, y_pred)
rmse_builtin = np.sqrt(mse_builtin)
r2_builtin = r2_score(y_test, y_pred)

print("\nBUILT-IN METRICS")
print("MAE  =", mae_builtin)
print("MSE  =", mse_builtin)
print("RMSE =", rmse_builtin)
print("R2   =", r2_builtin)

print("MANUAL VS BUILT-IN COMPARISON")
print("MAE  :", mae_manual, " | ", mae_builtin)
print("MSE  :", mse_manual, " | ", mse_builtin)
print("RMSE :", rmse_manual, " | ", rmse_builtin)
print("R2   :", r2_manual, " | ", r2_builtin)


FIRST 10 FEATURE VALUES (X)
[[0.74908024]
 [1.90142861]
 [1.46398788]
 [1.19731697]
 [0.31203728]
 [0.31198904]
 [0.11616722]
 [1.73235229]
 [1.20223002]
 [1.41614516]]

FIRST 10 TARGET VALUES (y)
[6.33428778 9.40527849 8.48372443 5.60438199 4.71643995 5.29307969
 5.82639572 8.67878666 6.79819647 7.74667842]

TRAINING DATA SIZE
(80, 1)

TESTING DATA SIZE
(20, 1)

FIRST 10 PREDICTIONS
[4.49875411 9.15273606 8.46643942 7.85214193 5.59173117 6.6071719
 5.77852817 8.975125   4.25815864 6.23983135]

MANUAL METRICS
MAE  = 0.5913425779189777
MSE  = 0.6536995137170021
RMSE = 0.8085168605026132
R2   = 0.8072059636181392

BUILT-IN METRICS
MAE  = 0.5913425779189777
MSE  = 0.6536995137170021
RMSE = 0.8085168605026132
R2   = 0.8072059636181392
MANUAL VS BUILT-IN COMPARISON
MAE  : 0.5913425779189777  |  0.5913425779189777
MSE  : 0.6536995137170021  |  0.6536995137170021
RMSE : 0.8085168605026132  |  0.8085168605026132
R2   : 0.8072059636181392  |  0.8072059636181392


In [9]:
#classificaiton model from stratch and builtin

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)
# load dataset
df = pd.read_csv("cancer.csv")
print(df.shape)

# remove fully empty columns
df = df.dropna(axis=1, how='all')
print(df.shape)
# remove id column if exists
if 'id' in df.columns:
    df = df.drop(columns=['id'])
    
# target
y = df['diagnosis']
# features
X = df.drop(columns=['diagnosis'])
print(X.shape)

# encode target
y = y.map({'M':1, 'B':0})

# scaling
scaler = StandardScaler()
X = scaler.fit_transform(X)

print("Scaling successful")

(569, 33)
(569, 32)
(569, 30)
Scaling successful


In [8]:

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)


model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("\nPREDICTIONS")
print(y_pred[:10])

TP = 0
TN = 0
FP = 0
FN = 0
for actual, predicted in zip(y_test, y_pred):
    # True Positive
    if actual == 1 and predicted == 1:
        TP += 1
    # True Negative
    elif actual == 0 and predicted == 0:
        TN += 1
    # False Positive
    elif actual == 0 and predicted == 1:
        FP += 1
    # False Negative
    elif actual == 1 and predicted == 0:
        FN += 1

# display confusion matrix
print("\nCONFUSION MATRIX FROM SCRATCH")
print("TP =", TP)
print("TN =", TN)
print("FP =", FP)
print("FN =", FN)

# Accuracy
accuracy = (TP + TN) / (TP + TN + FP + FN)
# Precision
precision = TP / (TP + FP)
# Recall
recall = TP / (TP + FN)
# F1 Score
f1 = 2 * (
    (precision_manual * recall_manual)
    /
    (precision_manual + recall_manual)
)

print("\nMANUAL METRICS")
print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)
#built in metrics
accuracy_builtin = accuracy_score(y_test, y_pred)
precision_builtin = precision_score(y_test, y_pred)
recall_builtin = recall_score(y_test, y_pred)
f1_builtin = f1_score(y_test, y_pred)
cm_builtin = confusion_matrix(y_test, y_pred)

print("\nBUILT-IN METRICS")
print("Accuracy :", accuracy_builtin)
print("Precision:", precision_builtin)
print("Recall   :", recall_builtin)
print("F1 Score :", f1_builtin)
print("\nBUILT-IN CONFUSION MATRIX")
print(cm_builtin)


#manual vs builtin
print("Accuracy : ", accuracy_manual, " | ", accuracy_builtin)
print("Precision: ", precision_manual, " | ", precision_builtin)
print("Recall   : ", recall_manual, " | ", recall_builtin)
print("F1 Score : ", f1_manual, " | ", f1_builtin)



PREDICTIONS
[0 1 1 0 0 1 1 1 0 0]

CONFUSION MATRIX FROM SCRATCH
TP = 41
TN = 70
FP = 1
FN = 2

MANUAL METRICS
Accuracy : 0.9736842105263158
Precision: 0.9761904761904762
Recall   : 0.9534883720930233
F1 Score : 0.9647058823529412

BUILT-IN METRICS
Accuracy : 0.9736842105263158
Precision: 0.9761904761904762
Recall   : 0.9534883720930233
F1 Score : 0.9647058823529412

BUILT-IN CONFUSION MATRIX
[[70  1]
 [ 2 41]]
Accuracy :  0.9736842105263158  |  0.9736842105263158
Precision:  0.9761904761904762  |  0.9761904761904762
Recall   :  0.9534883720930233  |  0.9534883720930233
F1 Score :  0.9647058823529412  |  0.9647058823529412
